// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Catapult")]
[assembly: AssemblyDescriptionAttribute("Catapult Launcher")]
[assembly: GuidAttribute("1c2e3e46-7e39-4c03-8816-ea2791fa184d")]
[assembly: AssemblyProductAttribute("Catapult")]
[assembly: AssemblyVersionAttribute("0.2.5")]
[assembly: AssemblyFileVersionAttribute("0.2.5")]
[assembly: AssemblyMetadataAttribute("SquirrelAwareVersion","1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.2.5";
    }
}
