// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("Catapult.Core")]
[assembly: GuidAttribute("a33d57d2-0a7f-4901-beab-a92382a033eb")]
[assembly: AssemblyProductAttribute("Catapult")]
[assembly: AssemblyVersionAttribute("0.2.5")]
[assembly: AssemblyFileVersionAttribute("0.2.5")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Catapult.Core";
        internal const System.String Guid = "a33d57d2-0a7f-4901-beab-a92382a033eb";
        internal const System.String AssemblyProduct = "Catapult";
        internal const System.String AssemblyVersion = "0.2.5";
        internal const System.String AssemblyFileVersion = "0.2.5";
    }
}
